/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: catl3rs (https://sketchfab.com/catwithantlers)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/banana-duck-e542871d099947de88212a4a86315a40
title: banana duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/bananaDuck.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group rotation={[0, 0, 0]}>
          <group position={[0, 0, 0]} rotation={[0, 0, 0]} scale={8}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.banana_peel}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.body}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.beak}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.eyes}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/bananaDuck.gltf')
