/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: bradacvojtech (https://sketchfab.com/bradacvojtech)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/clay-duck-39259b33b5b24361b91f2211f3e71691
title: Clay Duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/clayDuck.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 3.2, 0]}>
        <group rotation={[0, 0, 0]}>
          <group position={[35, -22, 0]} scale={0.22}>
            <mesh
              geometry={nodes.defaultMaterial.geometry}
              material={materials.lambert1}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/clayDuck.gltf')
