/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: alfredonicolasalarcon (https://sketchfab.com/alfredonicolasalarcon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/duck-1ef90928c6994bb28d8069069dd5adce
title: Duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Duck({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/duck.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]}>
          <group scale={0.01}>
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.material_0}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/duck.gltf')
