/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: BenEEmoon (https://sketchfab.com/BenEEmoon)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/molly-the-duck-d4aa4126fce64397935d128ed54c3def
title: Molly the Duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/MollyTheDuckling.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group rotation={[0, 0, 0]}>
          <group position={[-35, 15, 0]} scale={17}>
            <mesh
              geometry={nodes.Object_4.geometry}
              material={materials.Body}
            />
            <mesh
              geometry={nodes.Object_5.geometry}
              material={materials.Body}
            />
            <mesh
              geometry={nodes.Object_6.geometry}
              material={materials.Bill}
            />
            <mesh
              geometry={nodes.Object_7.geometry}
              material={materials.Bill}
            />
            <mesh
              geometry={nodes.Object_8.geometry}
              material={materials.Nostrils}
            />
            <mesh
              geometry={nodes.Object_9.geometry}
              material={materials.Legs}
            />
          </group>
          <group position={[-35, 15, 0]} scale={17}>
            <mesh
              geometry={nodes.Object_11.geometry}
              material={materials.Shirt}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/MollyTheDuckling.gltf')
