/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: Ikki_3d (https://sketchfab.com/ikki_3d)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/rubber-duck-f1de4fc390db4266a509b9739350512a
title: Rubber duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/rubberDuck.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[0, 0, 0]}>
        <group rotation={[4.9, 0, 0]}>
          <group position={[-35, 0, 15]} scale={0.16}>
            <mesh
              geometry={nodes.defaultMaterial.geometry}
              material={materials.material}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/rubberDuck.gltf')
