/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'
import { useFrame } from 'react-three-fiber'

export default function ClassicDuck({ ...props }) {
  const group = useRef()

  const { nodes, materials } = useGLTF(props.path)
  return (
    <group ref={group} {...props} dispose={null}>
      <group scale={5}>
        <mesh geometry={nodes.duck1.geometry} material={nodes.duck1.material} />
      </group>
    </group>
  )
}

useGLTF.preload('/Pato.glb')
