/*
Auto-generated by: https://github.com/pmndrs/gltfjsx
author: RafaelScopel (https://sketchfab.com/RafaelScopel)
license: CC-BY-4.0 (http://creativecommons.org/licenses/by/4.0/)
source: https://sketchfab.com/3d-models/duck-duck-duck-faf58bd8859744a2ac73719fefc5b454
title: Duck duck duck
*/

import React, { useRef } from 'react'
import { useGLTF } from '@react-three/drei'

export default function Model({ ...props }) {
  const group = useRef()
  const { nodes, materials } = useGLTF('/happyDuck.gltf')
  return (
    <group ref={group} {...props} dispose={null}>
      <group rotation={[-Math.PI / 2, 0, 0]}>
        <group rotation={[Math.PI / 2, 0, 0]} scale={0.3}>
          <group position={[-140, -70, 0]} scale={0.12}>
            <mesh
              geometry={nodes.Duck_Duck_0.geometry}
              material={materials.Duck}
            />
          </group>
        </group>
      </group>
    </group>
  )
}

useGLTF.preload('/happyDuck.gltf')
